// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package questing

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// EndQuest is the `endQuest` instruction.
type EndQuest struct {
	QuestIndex              *uint64
	DepositTokenAccountBump *uint8

	// [0] = [WRITE, SIGNER] initializer
	//
	// [1] = [WRITE] depositTokenAccount
	//
	// [2] = [WRITE] pixelballzMint
	//
	// [3] = [WRITE] pixelballzTokenAccount
	//
	// [4] = [WRITE] questAccount
	//
	// [5] = [] tokenProgram
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewEndQuestInstructionBuilder creates a new `EndQuest` instruction builder.
func NewEndQuestInstructionBuilder() *EndQuest {
	nd := &EndQuest{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 6),
	}
	return nd
}

// SetQuestIndex sets the "questIndex" parameter.
func (inst *EndQuest) SetQuestIndex(questIndex uint64) *EndQuest {
	inst.QuestIndex = &questIndex
	return inst
}

// SetDepositTokenAccountBump sets the "depositTokenAccountBump" parameter.
func (inst *EndQuest) SetDepositTokenAccountBump(depositTokenAccountBump uint8) *EndQuest {
	inst.DepositTokenAccountBump = &depositTokenAccountBump
	return inst
}

// SetInitializerAccount sets the "initializer" account.
func (inst *EndQuest) SetInitializerAccount(initializer ag_solanago.PublicKey) *EndQuest {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(initializer).WRITE().SIGNER()
	return inst
}

// GetInitializerAccount gets the "initializer" account.
func (inst *EndQuest) GetInitializerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetDepositTokenAccountAccount sets the "depositTokenAccount" account.
func (inst *EndQuest) SetDepositTokenAccountAccount(depositTokenAccount ag_solanago.PublicKey) *EndQuest {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(depositTokenAccount).WRITE()
	return inst
}

// GetDepositTokenAccountAccount gets the "depositTokenAccount" account.
func (inst *EndQuest) GetDepositTokenAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetPixelballzMintAccount sets the "pixelballzMint" account.
func (inst *EndQuest) SetPixelballzMintAccount(pixelballzMint ag_solanago.PublicKey) *EndQuest {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(pixelballzMint).WRITE()
	return inst
}

// GetPixelballzMintAccount gets the "pixelballzMint" account.
func (inst *EndQuest) GetPixelballzMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetPixelballzTokenAccountAccount sets the "pixelballzTokenAccount" account.
func (inst *EndQuest) SetPixelballzTokenAccountAccount(pixelballzTokenAccount ag_solanago.PublicKey) *EndQuest {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(pixelballzTokenAccount).WRITE()
	return inst
}

// GetPixelballzTokenAccountAccount gets the "pixelballzTokenAccount" account.
func (inst *EndQuest) GetPixelballzTokenAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetQuestAccountAccount sets the "questAccount" account.
func (inst *EndQuest) SetQuestAccountAccount(questAccount ag_solanago.PublicKey) *EndQuest {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(questAccount).WRITE()
	return inst
}

// GetQuestAccountAccount gets the "questAccount" account.
func (inst *EndQuest) GetQuestAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetTokenProgramAccount sets the "tokenProgram" account.
func (inst *EndQuest) SetTokenProgramAccount(tokenProgram ag_solanago.PublicKey) *EndQuest {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(tokenProgram)
	return inst
}

// GetTokenProgramAccount gets the "tokenProgram" account.
func (inst *EndQuest) GetTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

func (inst EndQuest) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_EndQuest,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst EndQuest) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *EndQuest) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.QuestIndex == nil {
			return errors.New("QuestIndex parameter is not set")
		}
		if inst.DepositTokenAccountBump == nil {
			return errors.New("DepositTokenAccountBump parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Initializer is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.DepositTokenAccount is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.PixelballzMint is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.PixelballzTokenAccount is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.QuestAccount is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.TokenProgram is not set")
		}
	}
	return nil
}

func (inst *EndQuest) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("EndQuest")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=2]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("             QuestIndex", *inst.QuestIndex))
						paramsBranch.Child(ag_format.Param("DepositTokenAccountBump", *inst.DepositTokenAccountBump))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=6]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("    initializer", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("   depositToken", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta(" pixelballzMint", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("pixelballzToken", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("          quest", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("   tokenProgram", inst.AccountMetaSlice.Get(5)))
					})
				})
		})
}

func (obj EndQuest) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `QuestIndex` param:
	err = encoder.Encode(obj.QuestIndex)
	if err != nil {
		return err
	}
	// Serialize `DepositTokenAccountBump` param:
	err = encoder.Encode(obj.DepositTokenAccountBump)
	if err != nil {
		return err
	}
	return nil
}
func (obj *EndQuest) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `QuestIndex`:
	err = decoder.Decode(&obj.QuestIndex)
	if err != nil {
		return err
	}
	// Deserialize `DepositTokenAccountBump`:
	err = decoder.Decode(&obj.DepositTokenAccountBump)
	if err != nil {
		return err
	}
	return nil
}

// NewEndQuestInstruction declares a new EndQuest instruction with the provided parameters and accounts.
func NewEndQuestInstruction(
	// Parameters:
	questIndex uint64,
	depositTokenAccountBump uint8,
	// Accounts:
	initializer ag_solanago.PublicKey,
	depositTokenAccount ag_solanago.PublicKey,
	pixelballzMint ag_solanago.PublicKey,
	pixelballzTokenAccount ag_solanago.PublicKey,
	questAccount ag_solanago.PublicKey,
	tokenProgram ag_solanago.PublicKey) *EndQuest {
	return NewEndQuestInstructionBuilder().
		SetQuestIndex(questIndex).
		SetDepositTokenAccountBump(depositTokenAccountBump).
		SetInitializerAccount(initializer).
		SetDepositTokenAccountAccount(depositTokenAccount).
		SetPixelballzMintAccount(pixelballzMint).
		SetPixelballzTokenAccountAccount(pixelballzTokenAccount).
		SetQuestAccountAccount(questAccount).
		SetTokenProgramAccount(tokenProgram)
}
