// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package someplace

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// EnableBatchUploading is the `enableBatchUploading` instruction.
type EnableBatchUploading struct {

	// [0] = [WRITE] batches
	//
	// [1] = [WRITE, SIGNER] oracle
	//
	// [2] = [] systemProgram
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewEnableBatchUploadingInstructionBuilder creates a new `EnableBatchUploading` instruction builder.
func NewEnableBatchUploadingInstructionBuilder() *EnableBatchUploading {
	nd := &EnableBatchUploading{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 3),
	}
	return nd
}

// SetBatchesAccount sets the "batches" account.
func (inst *EnableBatchUploading) SetBatchesAccount(batches ag_solanago.PublicKey) *EnableBatchUploading {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(batches).WRITE()
	return inst
}

// GetBatchesAccount gets the "batches" account.
func (inst *EnableBatchUploading) GetBatchesAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetOracleAccount sets the "oracle" account.
func (inst *EnableBatchUploading) SetOracleAccount(oracle ag_solanago.PublicKey) *EnableBatchUploading {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(oracle).WRITE().SIGNER()
	return inst
}

// GetOracleAccount gets the "oracle" account.
func (inst *EnableBatchUploading) GetOracleAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *EnableBatchUploading) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *EnableBatchUploading {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *EnableBatchUploading) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

func (inst EnableBatchUploading) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_EnableBatchUploading,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst EnableBatchUploading) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *EnableBatchUploading) Validate() error {
	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Batches is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Oracle is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
	}
	return nil
}

func (inst *EnableBatchUploading) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("EnableBatchUploading")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=0]").ParentFunc(func(paramsBranch ag_treeout.Branches) {})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=3]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("      batches", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("       oracle", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("systemProgram", inst.AccountMetaSlice.Get(2)))
					})
				})
		})
}

func (obj EnableBatchUploading) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	return nil
}
func (obj *EnableBatchUploading) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	return nil
}

// NewEnableBatchUploadingInstruction declares a new EnableBatchUploading instruction with the provided parameters and accounts.
func NewEnableBatchUploadingInstruction(
	// Accounts:
	batches ag_solanago.PublicKey,
	oracle ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey) *EnableBatchUploading {
	return NewEnableBatchUploadingInstructionBuilder().
		SetBatchesAccount(batches).
		SetOracleAccount(oracle).
		SetSystemProgramAccount(systemProgram)
}
