// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package someplace

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// ModifyListing is the `modifyListing` instruction.
type ModifyListing struct {
	ConfigIndex    *uint64
	IsListed       *bool   `bin:"optional"`
	LifecycleStart *uint64 `bin:"optional"`
	Price          *uint64 `bin:"optional"`

	// [0] = [WRITE] batch
	//
	// [1] = [WRITE, SIGNER] oracle
	//
	// [2] = [] listing
	//
	// [3] = [] treasuryAuthority
	//
	// [4] = [] systemProgram
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewModifyListingInstructionBuilder creates a new `ModifyListing` instruction builder.
func NewModifyListingInstructionBuilder() *ModifyListing {
	nd := &ModifyListing{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 5),
	}
	return nd
}

// SetConfigIndex sets the "configIndex" parameter.
func (inst *ModifyListing) SetConfigIndex(configIndex uint64) *ModifyListing {
	inst.ConfigIndex = &configIndex
	return inst
}

// SetIsListed sets the "isListed" parameter.
func (inst *ModifyListing) SetIsListed(isListed bool) *ModifyListing {
	inst.IsListed = &isListed
	return inst
}

// SetLifecycleStart sets the "lifecycleStart" parameter.
func (inst *ModifyListing) SetLifecycleStart(lifecycleStart uint64) *ModifyListing {
	inst.LifecycleStart = &lifecycleStart
	return inst
}

// SetPrice sets the "price" parameter.
func (inst *ModifyListing) SetPrice(price uint64) *ModifyListing {
	inst.Price = &price
	return inst
}

// SetBatchAccount sets the "batch" account.
func (inst *ModifyListing) SetBatchAccount(batch ag_solanago.PublicKey) *ModifyListing {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(batch).WRITE()
	return inst
}

// GetBatchAccount gets the "batch" account.
func (inst *ModifyListing) GetBatchAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetOracleAccount sets the "oracle" account.
func (inst *ModifyListing) SetOracleAccount(oracle ag_solanago.PublicKey) *ModifyListing {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(oracle).WRITE().SIGNER()
	return inst
}

// GetOracleAccount gets the "oracle" account.
func (inst *ModifyListing) GetOracleAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetListingAccount sets the "listing" account.
func (inst *ModifyListing) SetListingAccount(listing ag_solanago.PublicKey) *ModifyListing {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(listing)
	return inst
}

// GetListingAccount gets the "listing" account.
func (inst *ModifyListing) GetListingAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetTreasuryAuthorityAccount sets the "treasuryAuthority" account.
func (inst *ModifyListing) SetTreasuryAuthorityAccount(treasuryAuthority ag_solanago.PublicKey) *ModifyListing {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(treasuryAuthority)
	return inst
}

// GetTreasuryAuthorityAccount gets the "treasuryAuthority" account.
func (inst *ModifyListing) GetTreasuryAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *ModifyListing) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *ModifyListing {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *ModifyListing) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

func (inst ModifyListing) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_ModifyListing,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst ModifyListing) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *ModifyListing) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.ConfigIndex == nil {
			return errors.New("ConfigIndex parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Batch is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Oracle is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.Listing is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.TreasuryAuthority is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
	}
	return nil
}

func (inst *ModifyListing) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("ModifyListing")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=4]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("   ConfigIndex", *inst.ConfigIndex))
						paramsBranch.Child(ag_format.Param("      IsListed (OPT)", inst.IsListed))
						paramsBranch.Child(ag_format.Param("LifecycleStart (OPT)", inst.LifecycleStart))
						paramsBranch.Child(ag_format.Param("         Price (OPT)", inst.Price))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=5]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("            batch", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("           oracle", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("          listing", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("treasuryAuthority", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("    systemProgram", inst.AccountMetaSlice.Get(4)))
					})
				})
		})
}

func (obj ModifyListing) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `ConfigIndex` param:
	err = encoder.Encode(obj.ConfigIndex)
	if err != nil {
		return err
	}
	// Serialize `IsListed` param (optional):
	{
		if obj.IsListed == nil {
			err = encoder.WriteBool(false)
			if err != nil {
				return err
			}
		} else {
			err = encoder.WriteBool(true)
			if err != nil {
				return err
			}
			err = encoder.Encode(obj.IsListed)
			if err != nil {
				return err
			}
		}
	}
	// Serialize `LifecycleStart` param (optional):
	{
		if obj.LifecycleStart == nil {
			err = encoder.WriteBool(false)
			if err != nil {
				return err
			}
		} else {
			err = encoder.WriteBool(true)
			if err != nil {
				return err
			}
			err = encoder.Encode(obj.LifecycleStart)
			if err != nil {
				return err
			}
		}
	}
	// Serialize `Price` param (optional):
	{
		if obj.Price == nil {
			err = encoder.WriteBool(false)
			if err != nil {
				return err
			}
		} else {
			err = encoder.WriteBool(true)
			if err != nil {
				return err
			}
			err = encoder.Encode(obj.Price)
			if err != nil {
				return err
			}
		}
	}
	return nil
}
func (obj *ModifyListing) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `ConfigIndex`:
	err = decoder.Decode(&obj.ConfigIndex)
	if err != nil {
		return err
	}
	// Deserialize `IsListed` (optional):
	{
		ok, err := decoder.ReadBool()
		if err != nil {
			return err
		}
		if ok {
			err = decoder.Decode(&obj.IsListed)
			if err != nil {
				return err
			}
		}
	}
	// Deserialize `LifecycleStart` (optional):
	{
		ok, err := decoder.ReadBool()
		if err != nil {
			return err
		}
		if ok {
			err = decoder.Decode(&obj.LifecycleStart)
			if err != nil {
				return err
			}
		}
	}
	// Deserialize `Price` (optional):
	{
		ok, err := decoder.ReadBool()
		if err != nil {
			return err
		}
		if ok {
			err = decoder.Decode(&obj.Price)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

// NewModifyListingInstruction declares a new ModifyListing instruction with the provided parameters and accounts.
func NewModifyListingInstruction(
	// Parameters:
	configIndex uint64,
	isListed bool,
	lifecycleStart uint64,
	price uint64,
	// Accounts:
	batch ag_solanago.PublicKey,
	oracle ag_solanago.PublicKey,
	listing ag_solanago.PublicKey,
	treasuryAuthority ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey) *ModifyListing {
	return NewModifyListingInstructionBuilder().
		SetConfigIndex(configIndex).
		SetIsListed(isListed).
		SetLifecycleStart(lifecycleStart).
		SetPrice(price).
		SetBatchAccount(batch).
		SetOracleAccount(oracle).
		SetListingAccount(listing).
		SetTreasuryAuthorityAccount(treasuryAuthority).
		SetSystemProgramAccount(systemProgram)
}
